### ISSUE TITLE
Message About _.remove - Doesn't seem valid? 

### ISSUE THREAD

**Issue by adamsea** [lodash/lodash-migrate#10]
Hello,

I'm in the midst of using lodash-migrate to update 3.10.1 -> 4.1.0 and just got this message when using `_.remove`:

```
[ 'test1', 'Gluten Free' ]
lodash-migrate: _.remove([ 'Gluten Free' ], [Function])
  v3.10.1 => [ 'test1' ]
  v4.1.0 => []
```

The array printed above the message is the array passed to `_.remove` - it seems that the mutated array is what's in the message as a parameter (which is fine I suppose), the main issue is in the return array, which makes it appear as though the removed value is not returned from the method in 4.1.  This doesn't sync up with the changelog, docs, or source code.  Is this an issue with lodash-migrate flagging something that isn't really a problem, or might there be something else out-of-date on my side?

Thanks for your help!
-Eric

**Comment by jdalton** [comment]
Thanks!
