### ISSUE TITLE
runInContext problem

### ISSUE THREAD

**Issue by trkjgrdg** [lodash/lodash-migrate#12]
I load lodash-migrate as follows:

    define('lodash', [ 'lib/lodash/lodash-migrate' ], function(_) {
        return _.noConflict().runInContext({
            setTimeout : function() {return window.setTimeout.apply(this, arguments);}
        });
    });

It behaves as if I were using plain old lodash.  Even `_.max(['13', '22'], '1');` doesn't produce a warning.

**Comment by jdalton** [comment]
Closed by https://github.com/lodash/lodash-migrate/commit/f64b9308bda8f6daedc7dce0498a6b7149874e05.
