### ISSUE TITLE
_.each() runs loop twice

### ISSUE THREAD

**Issue by jcwren** [lodash/lodash-migrate#13]
I understand that `lodash-migrate` needs to compare the output of 3.10.1 to 4.3.0, but this breaks anything that builds an array within the loop.  The example produces this output:

$ node t.js
entry 1
entry 2
entry 3
entry 1
entry 2
entry 3
$

Given this, I'm not sure how one would use `lodash-migrate` in an actual application of any practical size. Wouldn't it be better to override the old methods, evaluate the arguments, and display a mapping to the new methods?

```javascript
var _ = require ('lodash-migrate');

var list = [
  'entry 1',
  'entry 2',
  'entry 3',
];

_.each (list, function (text) {
  console.log (text);
});```

**Comment by jdalton** [comment]
People do but thanks for the pessimism.
