### ISSUE TITLE
lodash-migrate breaks code that uses _.times

### ISSUE THREAD

**Issue by oliversalzburg** [lodash/lodash-migrate#18]
```js
var _ = require('lodash');
require('lodash-migrate');

_.times(2, function() {
  console.log('ohai');
});
```

The function passed to `_.times` will be run twice as many times as intended. Can have pretty nasty consequences and is pretty hard to wrap your head around when you encounter it.

**Comment by jdalton** [comment]
Ya, I recently patched this for `forEach` related methods but held off on this as `_.times` can return an array of results. Though I could probably lump it is as the result of it is unlikely to change.

**Comment by oliversalzburg** [comment]
@jdalton Awesome :+1:  Thanks for the quick fix :)
