### ISSUE TITLE
Should lodash-migrate always log output?

### ISSUE THREAD

**Issue by hawkrives** [lodash/lodash-migrate#2]
Using the example from the [curry docs](https://lodash.com/docs#curry), `lodash-migrate` never stops logging messages.

In short, running this code

```js
require('lodash-migrate')
var _ = require('lodash')

var abc = function(a, b, c) {
  return [a, b, c];
};

var curried = _.curry(abc);

console.log(curried(1)(2)(3))
// → [1, 2, 3]

console.log(curried(1, 2)(3))
// → [1, 2, 3]

console.log(curried(1, 2, 3))
// → [1, 2, 3]

// using placeholders
console.log(curried(1)(_, 3)(2))
// → [1, 2, 3]
```

produces

```
lodash-migrate: _.curry([Function])
  v3.0.0 => { [Function: wrapper]
  placeholder: 
   { [Function: lodash]
     support: 
...
  v3.0.0 => { [Function: wrapper]
  placeholder: 
   { [Function: lodash]
     support: 
...

[ 1, 2, 3 ]
[ 1, 2, 3 ]
[ 1, 2, 3 ]
[ 1, 2, 3 ]
```

From the docs and the code, I would expect a `2.4.1` and a `3.0.0` message, if there is some difference between the output. 

If there is not difference, though, I would expect no output.

Are my expectations incorrect?

I'm loving the new version, by the way. Excellent work.

**Comment by jdalton** [comment]
Thanks for catching this. I release `lodash-migrate` as `0.1.0` initially because I knew there would be issues to resolve. Tonight I'll make it less chatty for things it can't compare, like function results.
