### ISSUE TITLE
Cryptic messages (redux)

### ISSUE THREAD

**Issue by ryankeener** [lodash/lodash-migrate#22]
I'm seeing the same behavior as https://github.com/lodash/lodash-migrate/issues/7

```
lodash-migrate: _.contains('name email username platform_id', 'platform_id')
  v3.10.1 => true
  v4.5.1 => [TypeError: Cannot read property 'apply' of undefined]
```

It's not just `_.contains`, all logs contain the `Cannot read...` message

**Comment by jdalton** [comment]
Thanks for reporting this!

**Comment by jdalton** [comment]
btw what's the (redux) bit about?

**Comment by phated** [comment]
http://www.merriam-webster.com/dictionary/redux

**Comment by jdalton** [comment]
Regression?

**Comment by ryankeener** [comment]
@jdalton sorry about the 'redux', I realize it's kind of an esoteric word and could be confused with the React project.  Anyway, thanks for the fix, I'll check it out today!
