### ISSUE TITLE
Possible false positive warning.

### ISSUE THREAD

**Issue by just-boris** [lodash/lodash-migrate#24]
The simple code causes a warning for me:

```js
_.reduce(null, (a, b) => Math.max(a, b))
```

```
lodash-migrate: Method renamed
  v3.10.1 => _.callback
  v4.6.1 => _.iteratee
```
As I tested, there is nothing different in behavior between 3 and 4 version, I get the same result No matter what the real reduce function is, the issue happens when the first argument is `null` or `undefined`.

**Comment by jdalton** [comment]
It's because it's being called internally :)
The external use of that function is so slim that I can add an exception to just silence that specific warning.

**Comment by just-boris** [comment]
Now it works as expected. Thanks!
