### ISSUE TITLE
Should uniqueId be excluded from log?

### ISSUE THREAD

**Issue by szarouski** [lodash/lodash-migrate#26]
Hi, when lodash-migrate is running `_.uniqueId`, results will always be different and will be logged to console. I wonder if logging should be turned off just for uniqueId?

Thanks.

**Comment by jdalton** [comment]
`uniqueId` is based on an internal counter. Since both versions have the same counter and are executed together they should be in sync. Can you provide a snippet of the results you're getting?

**Comment by szarouski** [comment]
Sure
```
lodash-migrate: _.uniqueId()
  v3.10.1 => '108'
  v4.6.1 => '106'

lodash-migrate: _.uniqueId('empty')
  v3.10.1 => 'empty109'
  v4.6.1 => 'empty107'

lodash-migrate: _.uniqueId()
  v3.10.1 => '110'
  v4.6.1 => '108'

lodash-migrate: _.uniqueId('empty')
  v3.10.1 => 'empty111'
  v4.6.1 => 'empty109'
```

Most likely I'm doing something weird, but here is an archive with code (sorry for an archive, [I did run into a weird issue with npm](https://github.com/npm/npm/issues/10686), so I can't provide proper setup steps).

[temp.zip](https://github.com/lodash/lodash-migrate/files/190964/temp.zip)

To reproduce run `npm run test-node`.

Thank you

**Comment by jdalton** [comment]
It's probably getting called before being wrapped and causing a sync issue. I've added it to the ignore list.
