### ISSUE TITLE
Circular require('util') call in util.js?

### ISSUE THREAD

**Issue by onlywei** [lodash/lodash-migrate#28]
This is causing me pain when trying to load lodash-migrate using JSPM/SystemJS. It keeps trying to download an un-mapped "util.js" because of this `require('util')` call inside `lib/util.js`: https://github.com/lodash/lodash-migrate/blob/master/lib/util.js#L31

What's the reason for this `require()`?

**Comment by jdalton** [comment]
See https://nodejs.org/api/util.html#util_util_inspect_object_options.

**Comment by jdalton** [comment]
We have a pre-built version in the `dist` folder.
