### ISSUE TITLE
Console output garbled in browsers

### ISSUE THREAD

**Issue by royaldark** [lodash/lodash-migrate#3]
In browsers, `console.log` can't handle the control characters which color the messages. This makes errors extremely hard to read:
![screenshot from 2015-01-29 20 26 08](https://cloud.githubusercontent.com/assets/1669397/5970203/469cefae-a7f5-11e4-8867-7492bd2a1194.png)

**Comment by jdalton** [comment]
Hi @royaldark. I can detect `_.support.dom` and not color if it's true.

**Comment by jdalton** [comment]
Also thanks for browerifying this and trying it out. Super helpful.

**Comment by royaldark** [comment]
Awesome, that would be great. Thank you guys for making this tool! I wish every library released a tool like this.

**Comment by jdalton** [comment]
Ok published [0.1.3](https://www.npmjs.com/package/lodash-migrate) :smile_cat:
