### ISSUE TITLE
Usage of _.findWhere() is not logged

### ISSUE THREAD

**Issue by onlywei** [lodash/lodash-migrate#38]
I'm a little confused as to how `lodash-migrate` actually helps me to migrate to Lodash 4.x. Currently I get this in my console when I load lodash-migrate:

```
lodash-migrate: _.defer([Function])
  v3.10.1 => 82
  v4.13.1 => 83
```

`_.defer()` is not listed anywhere in the Lodash 4.x release notes / changelog. I'm not sure what's the significance of this line in my console.

However, in the changelog there **is** this line:
* Removed `_.findWhere` in favor of `_.find` with iteratee shorthand

So, I go and modify some of my `_.find` calls to `_.findWhere` just to see if `lodash-migrate` will give me any warnings, but it doesn't log anything when this code is executed!

There are also a few other things in the breaking change list, such as removal of `[thisArg]` that `lodash-migrate` does not log either.

I think I'm missing something major, because I currently cannot understand how `lodash-migrate` is supposed to help me migrate from 3.10.1 to 4.x. Is the purpose of `lodash-migrate` **only** to log messages? What is it that I am missing?

Right now I am loading Lodash 3.10.1 and then loading `lodash-migrate`. Should I be loading 4.x and then `lodash-migrate` instead?

**Comment by jdalton** [comment]
Hi @onlywei!

lodash-migrate wraps your older lodash and compares the results against the latest lodash, logging a message when the results don't match.

When I try to run `_.findWhere` I get:
```bash
lodash-migrate: _.findWhere([ { a: 1 } ], { a: 1 })
  v3.10.1 => { a: 1 }
  v4.13.1 => [TypeError: Cannot read property 'apply' of undefined]
```

You may find [eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash) helpful too.

**Comment by onlywei** [comment]
Thanks @jdalton -- this makes a lot more sense to me now. I thought about it some more, and I believe the reason why when `_.findWhere()` is executed in my code I don't get a log is because I am doing:

```js
import _ from 'lodash';

// this is an actual js file in my code that gets loaded
```

And then loading `lodash-migrate` asynchronously later. I believe that loading `lodash-migrate` at a later time cannot affect the `_` object that has already been imported into my code.

**Comment by jdalton** [comment]
If it's transpiling to Node style common-js it should as modules loaded are cached by `require.cache`.

**Comment by onlywei** [comment]
Negative, I am using JSPM/SystemJS to load this in the browser.

**Comment by jdalton** [comment]
Ah, neat.
