### ISSUE TITLE
Odd deprecation message

### ISSUE THREAD

**Issue by justin808** [lodash/lodash-migrate#4]
Should this message show the 2.4 version? I'm confused over what to make of this message.

```
 lodash-migrate: _.map([ , ,  ], [Function])
  v3.1.0 => [ { type: 'select',
    key: '0',
    ref: null,
    _owner: 
     { props: {...
  v3.1.0 => [ { type: 'select',
    key: '0',
    ref: null,
    _owner: 
     { props: {...
```

**Comment by jdalton** [comment]
> I'm confused over what to make of this message.

Same here.

How are you loading `lodash-migrate`?

`lodash-migrate` does a comparison of values using `isEqual` which has some limitations.
What kind of collection are you iterating?

**Comment by jdalton** [comment]
lodash v2 should be loaded as `require('lodash')` and then after `require(lodash-migrate')` should be called. You can see how it loads and wraps things [here](https://github.com/lodash/lodash-migrate/blob/0.1.3/index.js#L1-L2).

**Comment by justin808** [comment]
The collections is an array of 3 undefined:

```
   var benchmarksSelects = _.map(new Array(3), function(_, index)  {
```

**Comment by jdalton** [comment]
Ok. It looks like you're loading `lodash-migrate` incorrectly. Are you loading v2.4.1 as `lodash`?

**Comment by justin808** [comment]
@jdalton, this is in my npm-shrinkwrap.json. Maybe some library is loading it?

```
    "lodash": {
      "version": "3.1.0",
      "from": "lodash@>=3.1.0 <4.0.0",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-3.1.0.tgz"
    },
```

**Comment by jdalton** [comment]
Yap. You should use `lodash-migrate` when testing older lodash versions. It's not intended for testing against itself :P

**Comment by jdalton** [comment]
I'll see if I can make it less chatty for the cases `isEqual` has trouble with.
