### ISSUE TITLE
Feature request: ability to provide custom logger function

### ISSUE THREAD

**Issue by jasonkarns** [lodash/lodash-migrate#44]
I would love to use this module in a few of our apps, but we have a bunch of other logging infrastructure in place that would make simple console logs hard to find.

It would be awesome if we could provide our own logging function, that way we can tie it into its own bunyan logger and/or alter the logging level appropriately. (Or even wrap the message with some pre/post output.)

Thoughts? I can submit a PR if the idea is well received.

**Comment by jdalton** [comment]
I'm up for it! A PR would be rad.

**Comment by jasonkarns** [comment]
I assume the ability for lodash-migrate to return the old lodash is still desired? IMO, it would improve the api if the lodash-migrate require just returned a function that accepted configuration options. Clearly, browser usage has no need for the return value, anyway. And node usage of this module is likely to only `require` lodash-migrate at the app entry point, not to replace every existing `require('lodash')`, so it isn't really a huge difference between adding the lodash-migrate require and replacing the old require.

But dropping the old return behavior would obviously be a breaking change...

**Comment by jdalton** [comment]
Breaking changes away, it's pre-1.0.

**Comment by jdalton** [comment]
Moved to #45.
