### ISSUE TITLE
Incorrect  _.bind when (ab?)using _.find with property shorthand and a thisArg

### ISSUE THREAD

**Issue by davidshepherd7** [lodash/lodash-migrate#46]
In 3.10 it was possible to use a three argument shorthand for find, such that this

    _.find(collection, 'id', x);

is equivalent in 4.13 to

    _.find(collection, ['id', x]);

However the codemod outputs

    _.find(collection, _.bind('id', x));

which fails. This "feature" doesn't seem to have been documented anywhere, so I think it's an unintended consequence of combining `thisArg` and `_.matchesProperty`.  I suspect the same thing  worked for all functions that could take a property shorthand and a `thisArg`.

But anyway it somehow it got used in a few places in our code base, so I thought you might like to know that the codemod doesn't deal with it. Maybe you could add a note in the readme, or even implement the migration?

**Comment by jdalton** [comment]
Hi @davidshepherd7!

I think you're wanting the [lodash-codemods](https://github.com/jfmengels/lodash-codemods) repo.

**Comment by davidshepherd7** [comment]
Oops, yeah, very sorry!
