### ISSUE TITLE
Missing migration/warning for use of each/forEach/etc. inside chains

### ISSUE THREAD

**Issue by davidshepherd7** [lodash/lodash-migrate#47]
The [third bullet point of the 4.0.0 changelog](https://github.com/lodash/lodash/wiki/Changelog#jan-12-2016--diff--docs) doesn't seem to be handled by the codemod.

It should probably remove the `.value()` if the `forEach` is the final call in the chain, and give a warning otherwise.

P. S. Thanks so much for making this, it's been really helpful for our migration!

**Comment by jdalton** [comment]
I think you're wanting the [lodash-codemods](https://github.com/jfmengels/lodash-codemods) repo.

Related to #46.
