### ISSUE TITLE
Extract out lodash-migrate-instrument.

### ISSUE THREAD

**Issue by jdalton** [lodash/lodash-migrate#5]
Extract out lodash-migrate-instrument to work with other versions of lodash or underscore similar to [the work being done](https://github.com/lodash/lodash-fp/issues/6) in [lodash-fp](https://github.com/lodash/lodash-fp/).

**Comment by jdalton** [comment]
This is a nice enhancement but I don't think it's going to happen.

**Comment by jasonkarns** [comment]
that's a shame. my current legacy codebase has started using lodash for new stuff, but there is a bunch of underscore lying around. I would have loved to drop in a mythical underscore-migrate module that does the same as this module but for underscore -> lodash.

**Comment by jdalton** [comment]
PR's would be accepted :D
