### ISSUE TITLE
Which version I should be running

### ISSUE THREAD

**Issue by chamini2** [lodash/lodash-migrate#51]
I have a very used function which used `_.pick` with the second argument as a function, meaning that the output of `lodash-migrate` tells me about the different results a lot; so I figured I should change the `_.pick` to the new `_.pickBy`, but now it says `_.pickBy is not a function`.

How could I got around this to start using lodash 4 while still using the lodash-migrate module to finish the migration

**Comment by chamini2** [comment]
I'm currently using it like `const _  = require('lodash-migrate')`

**Comment by jdalton** [comment]
Hi @chamini2!

The next release will allow you to customize the logger:
```js
const migrate = require('lodash-migrate')
migrate({
  'log': function(value) { /* customize */ }
});
```

You might also check out [lodash-codemods](https://www.npmjs.com/package/lodash-codemods) &
[eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash) to help migrate pre-4 lodash code to the latest release.
