### ISSUE TITLE
Master and latest tag (0.3.0) have diverged

### ISSUE THREAD

**Issue by jasonkarns** [lodash/lodash-migrate#54]
Looks like the 0.3.0 tag was made on the wrong commit? Or perhaps some more changes to master were made off the wrong commit?

Either way, it appears that master has diverged from 0.3.0. If the 0.3.0 tag is "good", I would imagine we should rebase master off it.

![image](https://cloud.githubusercontent.com/assets/119972/17105736/72d6846a-5256-11e6-9a64-2f7202f1bd9f.png)

**Comment by jdalton** [comment]
Fixed, thanks!
