### ISSUE TITLE
Lodash 2.4.1 upgrade

### ISSUE THREAD

**Issue by mattrw89** [lodash/lodash-migrate#58]
Hello, 

I'm using a pretty old version of lodash in my applications and would love to upgrade, but am fairly hesitant to do so because of my extensive use of lodash. 

Is there documentation somewhere describing what lodash-migrate can and cannot do in terms of describing the required changes?

Can it get me from 2.4.1 to 3.x? or 2.4.1 to 4.x?

Do you have any recommendations on how to best migrate to 4.x? Go through 3.x?

Thanks,
Matt

**Comment by jdalton** [comment]
Hi @mattrw89,

Hurray on upgrading! The current versions of `lodash-migrate` go from an older lodash to v4.
You can use [v0.1.6](https://github.com/lodash/lodash-migrate/tree/0.1.6) if you'd like to go from an older lodash to v3.

You should also check out  [lodash-codemods](https://www.npmjs.com/package/lodash-codemods), &
[eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash).
