### ISSUE TITLE
Eliminate implicit altering of states on initialization

### ISSUE THREAD

**Issue by pauljoey** [lodash/lodash-migrate#60]
Good day! 

To provide better support for more uses of lodash-migrate, particularly in non-`<script>`-based usage such as async/module/package systems, I think that it would be preferable to opt for a more explicit usage pattern for the module's core that does not alter any global or dependency states implicitly upon initialization (monkey-patching). Plus you can eliminate your dependency on lodash.

Change usage pattern

    var _ = require('lodash');
    require('lodash-migrate'); 
    // `_` is now magically altered

To

    var _ = require('lodash');
    var migrate = require('lodash-migrate'); 
    var v2 = migrate(_);
    
The current behaviour could be implemented by way of a small auxiliary file `lodash-migrate-monkeypatch.js` included in the dist directory (or even a separate module). 

Alternatively you could eliminate the monkey-patch behaviour by exporting the modified lodash from the module

    import _v4 from 'lodash'
    import { _v2 } from 'lodash-migrate'

or

    var _v4 = require('lodash');
    var _v2 = require('lodash-migrate')._;

**Comment by jdalton** [comment]
Hi @pauljoey!

I dig our current approach because it shouldn't require rewriting large swaths of your project's files.
