### ISSUE TITLE
Usage in a browser and better example for custom logging options

### ISSUE THREAD

**Issue by dwiyatci** [lodash/lodash-migrate#61]
Hello there,

I'm trying lodash-migrate out in [my fiddle](https://jsfiddle.net/glenn/jnr2v6x3/), but I can't seem to get anything out of the console. What did I do wrong?

Furthermore, what do I need to pass as `log`, `migrateMessage`, and `renameMessage` properties for custom logging? I've got a feeling that the readme doc doesn't really provide sufficient info on this.

Cheers! :)

**Comment by jdalton** [comment]
Thanks @dwiyatci!

I've renamed the UMD export to avoid the problem.
See https://output.jsbin.com/beyoti/.
