### ISSUE TITLE
Add warning about production usage in readme

### ISSUE THREAD

**Issue by walling** [lodash/lodash-migrate#68]
We ran this on a big project, but had some major issues, which could nice to have been warned about. For one there's a big performance hit on running this in production. Furthermore if you have any non-functional functions, it could be an issue, like fx.:

```js
_.map(foo, function() { /* changing some state here */ })
```

The map function will be invoked twice, which means your state might be corrupted.

Adding a paragraph about these limitations in the readme, would be appreciated.

**Comment by jdalton** [comment]
Serves you right! 😈 

A migration tool in production is the worst thing ever. I purposely made Lodash's less robust so folks wouldn't be encouraged to do so. I've seen how devs misuse jquery-migrate 😋 

Would you be up for writing up a warning and making a PR?

**Comment by walling** [comment]
We learned it the hard way, I guess. I'm not exactly sure what you mean by _"I purposely made Lodash's less robust"_ though. :)

I will send a PR about the readme, probably tomorrow.

**Comment by jdalton** [comment]
That was a typo on my part. Supposed to be "purposely made `lodash-migrate` less robust".
