### ISSUE TITLE
cryptic log messages

### ISSUE THREAD

**Issue by chino23** [lodash/lodash-migrate#7]
Hi,

I've had some issues migrating form 2.4.1 to 3.x and this library doesn't really help me, unfortunately.

I just get a lot of issues like:

````
lodash-migrate: _.createCallback({ status: 'archive' }, undefined, 3)
  v2.4.1 => [Function]
  v3.6.0 => [TypeError: Cannot read property 'apply' of undefined]
````

But the callback function is never used explicitly. I have no idea which lodash call that belongs to and how to fix it. 

Is there a way to better mark the source function?

**Comment by jdalton** [comment]
This is a bug as lodash-migrate is attempting to call `_.createCallback` which has been removed in v3. I'll patch this up and publish a bump asap.

**Comment by jdalton** [comment]
Bumped & published.

**Comment by chino23** [comment]
Thanks a lot, @jdalton. That was quick!

**Comment by ryankeener** [comment]
Attempting to use this for v3->v4 and getting these messages on all output:

```
lodash-migrate: _.contains('name email username platform_id', 'platform_id')
  v3.10.1 => true
  v4.5.1 => [TypeError: Cannot read property 'apply' of undefined]
```

**Comment by jdalton** [comment]
@ryankeener Can you open a new issue.
