### ISSUE TITLE
requiring the module caused some odd transitions to occur in our app.

### ISSUE THREAD

**Issue by dadambickford** [lodash/lodash-migrate#8]
Didn't have any problems migrating, but it caused some funky transitions in our app after an action.

Generalized example

start at home page
click list button, go to list page.
click new item, go to add item page.
fill input, click enter
_should_ transition back to list, _actually_ transitions to list then quickly back home.

Behavior was solved by removing the `require('lodash-migrate')` from the file.

module version was 0.1.6. Our app is built with react using react-router for the transitions.

Sorry I don't have more info :confused: it was requested on twitter I still report this :smile:

**Comment by jdalton** [comment]
Could you try edge and see if this helps.

**Comment by dadambickford** [comment]
This issue actually popped it's head up again today, with out the lodash-migrate requires, so it might be an issue with v3.7.0 of lodash itself, but we can't reproduce it reliably to pinpoint a cause.
